Add company creation functionality
RuslanKhabibullinFs/pdp-subdomains pull request #1
Opened 2017-08-16 11:16 UTC by RuslanKhabibullinFs

https://trello.com/c/O2hWJfXj

2017-08-16 19:25 UTC, ArthurZaharov requested changes

2017-08-16 19:25 UTC, ArthurZaharov commented on app/forms/company_registration_form.rb
> +  validate :password_equality_check
Can you replace this with `validates :password, confirmation: true`?

2017-08-16 19:25 UTC, ArthurZaharov commented on app/models/user.rb
> +  def password_required?
Why you need this check? If you need it to update user info then maybe you can use Devise build in functionality - https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-account-without-providing-a-password

2017-08-16 19:25 UTC, ArthurZaharov commented on app/validators/uniqueness_validator.rb
> +class UniquenessValidator < ActiveRecord::Validations::UniquenessValidator
It isn't good idea to rewrite rails build in validator definitely.

2017-08-16 19:25 UTC, ArthurZaharov commented on app/views/company_registrations/new.html.slim
> +      .form-inputs
Can you add this classes in SimpleForm wrapper?

2017-08-16 19:25 UTC, ArthurZaharov commented on app/views/layouts/_flash_messages.html.slim
> +    div[class = "alert alert-#{key == "notice" ? "info" : "warning"}"]
If you need this key transformation for Bootstrap styles then you can try to do it from css side like suggested here - https://github.com/plataformatec/devise/issues/2051#issuecomment-254652729

2017-08-16 19:25 UTC, ArthurZaharov commented on lib/subdomains/base.rb
> +module Subdomains
Why you paste it in `lib` folder? In `lib` folder usually stored vendor code libraries. All code that you write should be in `app` folder

2017-08-16 19:25 UTC, ArthurZaharov commented on app/controllers/application_controller.rb
> +  def after_sign_in_path_for(_record)
Do you really need this method? Does `Devise` standard behaviour enough?

2017-08-16 19:25 UTC, ArthurZaharov commented on app/controllers/company_registrations_controller.rb
> +      return redirect_to(posts_url(subdomain: owner_company.subdomain), notice: t(".success"))
You shouldn't use return in controller actions.

2017-08-20 14:14 UTC, RuslanKhabibullinFs commented on app/models/user.rb
> +  def password_required?
After some investigation i found that this method is needed) Without it is impossible to implement the functional: the password is required during registration process. And is not needed during edit/update profile process. (I get this method from Devise validatable module - https://github.com/plataformatec/devise/blob/master/lib/devise/models/validatable.rb)

2017-09-04 08:38 UTC, merged